-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity aes128_shift_rows_hw is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    state_ce0 : OUT STD_LOGIC;
    state_we0 : OUT STD_LOGIC;
    state_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    state_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of aes128_shift_rows_hw is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_2_fu_103_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_2_reg_192 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_5_fu_109_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_reg_197 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond_fu_97_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_addr_reg_203 : STD_LOGIC_VECTOR (3 downto 0);
    signal state_addr_1_reg_208 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_3_fu_147_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_3_reg_216 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_6_reg_221 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal j_fu_159_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal j_reg_229 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal exitcond_i_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_reg_62 : STD_LOGIC_VECTOR (2 downto 0);
    signal exitcond1_i_fu_141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_i_reg_74 : STD_LOGIC_VECTOR (1 downto 0);
    signal j_i_reg_85 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_s_fu_121_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_i2_cast_fu_132_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum2_i_cast_fu_172_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum4_i_cast_fu_184_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_113_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_i2_fu_126_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_i_cast_fu_137_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sum2_i_fu_165_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum4_i_fu_177_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_i_reg_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_i_fu_153_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_i_reg_74 <= i_3_reg_216;
            elsif (((exitcond_fu_97_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_i_reg_74 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    i_reg_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_i_fu_141_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_reg_62 <= i_2_reg_192;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_62 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    j_i_reg_85_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                j_i_reg_85 <= j_reg_229;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                j_i_reg_85 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_2_reg_192 <= i_2_fu_103_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                i_3_reg_216 <= i_3_fu_147_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                j_reg_229 <= j_fu_159_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_fu_97_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    state_addr_1_reg_208(3 downto 2) <= sum_i2_cast_fu_132_p1(4 - 1 downto 0)(3 downto 2);
                    state_addr_reg_203(3 downto 2) <= tmp_s_fu_121_p1(4 - 1 downto 0)(3 downto 2);
                tmp_5_reg_197 <= tmp_5_fu_109_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_6_reg_221 <= state_q0;
            end if;
        end if;
    end process;
    state_addr_reg_203(1 downto 0) <= "00";
    state_addr_1_reg_208(1 downto 0) <= "11";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond_fu_97_p2, ap_CS_fsm_state3, ap_CS_fsm_state5, exitcond_i_fu_153_p2, exitcond1_i_fu_141_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond_fu_97_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((exitcond1_i_fu_141_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((exitcond_i_fu_153_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond_fu_97_p2)
    begin
        if ((((exitcond_fu_97_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond_fu_97_p2)
    begin
        if (((exitcond_fu_97_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond1_i_fu_141_p2 <= "1" when (i_i_cast_fu_137_p1 = i_reg_62) else "0";
    exitcond_fu_97_p2 <= "1" when (i_reg_62 = ap_const_lv3_4) else "0";
    exitcond_i_fu_153_p2 <= "1" when (j_i_reg_85 = ap_const_lv2_3) else "0";
    i_2_fu_103_p2 <= std_logic_vector(unsigned(i_reg_62) + unsigned(ap_const_lv3_1));
    i_3_fu_147_p2 <= std_logic_vector(unsigned(i_i_reg_74) + unsigned(ap_const_lv2_1));
    i_i_cast_fu_137_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_i_reg_74),3));
    j_fu_159_p2 <= std_logic_vector(unsigned(j_i_reg_85) + unsigned(ap_const_lv2_1));

    state_address0_assign_proc : process(state_addr_reg_203, state_addr_1_reg_208, ap_CS_fsm_state3, ap_CS_fsm_state5, exitcond_i_fu_153_p2, ap_CS_fsm_state6, sum2_i_cast_fu_172_p1, sum4_i_cast_fu_184_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_address0 <= sum4_i_cast_fu_184_p1(4 - 1 downto 0);
        elsif (((exitcond_i_fu_153_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            state_address0 <= state_addr_1_reg_208;
        elsif (((exitcond_i_fu_153_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            state_address0 <= sum2_i_cast_fu_172_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            state_address0 <= state_addr_reg_203;
        else 
            state_address0 <= "XXXX";
        end if; 
    end process;


    state_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5, exitcond_i_fu_153_p2, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((exitcond_i_fu_153_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((exitcond_i_fu_153_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            state_ce0 <= ap_const_logic_1;
        else 
            state_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    state_d0_assign_proc : process(state_q0, tmp_6_reg_221, ap_CS_fsm_state5, exitcond_i_fu_153_p2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_d0 <= state_q0;
        elsif (((exitcond_i_fu_153_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            state_d0 <= tmp_6_reg_221;
        else 
            state_d0 <= "XXXXXXXX";
        end if; 
    end process;


    state_we0_assign_proc : process(ap_CS_fsm_state5, exitcond_i_fu_153_p2, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((exitcond_i_fu_153_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            state_we0 <= ap_const_logic_1;
        else 
            state_we0 <= ap_const_logic_0;
        end if; 
    end process;

    sum2_i_cast_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum2_i_fu_165_p3),64));
    sum2_i_fu_165_p3 <= (tmp_5_reg_197 & j_fu_159_p2);
    sum4_i_cast_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum4_i_fu_177_p3),64));
    sum4_i_fu_177_p3 <= (tmp_5_reg_197 & j_i_reg_85);
    sum_i2_cast_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum_i2_fu_126_p2),64));
    sum_i2_fu_126_p2 <= (tmp_fu_113_p3 or ap_const_lv4_3);
    tmp_5_fu_109_p1 <= i_reg_62(2 - 1 downto 0);
    tmp_fu_113_p3 <= (tmp_5_fu_109_p1 & ap_const_lv2_0);
    tmp_s_fu_121_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_113_p3),64));
end behav;
