// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module aes128_shift_rows_hw (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_address0,
        state_ce0,
        state_we0,
        state_d0,
        state_q0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] state_address0;
output   state_ce0;
output   state_we0;
output  [7:0] state_d0;
input  [7:0] state_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] state_address0;
reg state_ce0;
reg state_we0;
reg[7:0] state_d0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] i_2_fu_103_p2;
reg   [2:0] i_2_reg_192;
wire    ap_CS_fsm_state2;
wire   [1:0] tmp_5_fu_109_p1;
reg   [1:0] tmp_5_reg_197;
wire   [0:0] exitcond_fu_97_p2;
reg   [3:0] state_addr_reg_203;
reg   [3:0] state_addr_1_reg_208;
wire   [1:0] i_3_fu_147_p2;
reg   [1:0] i_3_reg_216;
wire    ap_CS_fsm_state3;
reg   [7:0] tmp_6_reg_221;
wire    ap_CS_fsm_state4;
wire   [1:0] j_fu_159_p2;
reg   [1:0] j_reg_229;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond_i_fu_153_p2;
reg   [2:0] i_reg_62;
wire   [0:0] exitcond1_i_fu_141_p2;
reg   [1:0] i_i_reg_74;
reg   [1:0] j_i_reg_85;
wire    ap_CS_fsm_state6;
wire   [63:0] tmp_s_fu_121_p1;
wire   [63:0] sum_i2_cast_fu_132_p1;
wire   [63:0] sum2_i_cast_fu_172_p1;
wire   [63:0] sum4_i_cast_fu_184_p1;
wire   [3:0] tmp_fu_113_p3;
wire   [3:0] sum_i2_fu_126_p2;
wire   [2:0] i_i_cast_fu_137_p1;
wire   [3:0] sum2_i_fu_165_p3;
wire   [3:0] sum4_i_fu_177_p3;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_153_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_i_reg_74 <= i_3_reg_216;
    end else if (((exitcond_fu_97_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_i_reg_74 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_i_fu_141_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_62 <= i_2_reg_192;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_62 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        j_i_reg_85 <= j_reg_229;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        j_i_reg_85 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_2_reg_192 <= i_2_fu_103_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_3_reg_216 <= i_3_fu_147_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_reg_229 <= j_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_97_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        state_addr_1_reg_208[3 : 2] <= sum_i2_cast_fu_132_p1[3 : 2];
        state_addr_reg_203[3 : 2] <= tmp_s_fu_121_p1[3 : 2];
        tmp_5_reg_197 <= tmp_5_fu_109_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_6_reg_221 <= state_q0;
    end
end

always @ (*) begin
    if ((((exitcond_fu_97_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_97_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_address0 = sum4_i_cast_fu_184_p1;
    end else if (((exitcond_i_fu_153_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        state_address0 = state_addr_1_reg_208;
    end else if (((exitcond_i_fu_153_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        state_address0 = sum2_i_cast_fu_172_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_address0 = state_addr_reg_203;
    end else begin
        state_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state3) | ((exitcond_i_fu_153_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((exitcond_i_fu_153_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        state_ce0 = 1'b1;
    end else begin
        state_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_d0 = state_q0;
    end else if (((exitcond_i_fu_153_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        state_d0 = tmp_6_reg_221;
    end else begin
        state_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((exitcond_i_fu_153_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)))) begin
        state_we0 = 1'b1;
    end else begin
        state_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_fu_97_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond1_i_fu_141_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond_i_fu_153_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign exitcond1_i_fu_141_p2 = ((i_i_cast_fu_137_p1 == i_reg_62) ? 1'b1 : 1'b0);

assign exitcond_fu_97_p2 = ((i_reg_62 == 3'd4) ? 1'b1 : 1'b0);

assign exitcond_i_fu_153_p2 = ((j_i_reg_85 == 2'd3) ? 1'b1 : 1'b0);

assign i_2_fu_103_p2 = (i_reg_62 + 3'd1);

assign i_3_fu_147_p2 = (i_i_reg_74 + 2'd1);

assign i_i_cast_fu_137_p1 = i_i_reg_74;

assign j_fu_159_p2 = (j_i_reg_85 + 2'd1);

assign sum2_i_cast_fu_172_p1 = sum2_i_fu_165_p3;

assign sum2_i_fu_165_p3 = {{tmp_5_reg_197}, {j_fu_159_p2}};

assign sum4_i_cast_fu_184_p1 = sum4_i_fu_177_p3;

assign sum4_i_fu_177_p3 = {{tmp_5_reg_197}, {j_i_reg_85}};

assign sum_i2_cast_fu_132_p1 = sum_i2_fu_126_p2;

assign sum_i2_fu_126_p2 = (tmp_fu_113_p3 | 4'd3);

assign tmp_5_fu_109_p1 = i_reg_62[1:0];

assign tmp_fu_113_p3 = {{tmp_5_fu_109_p1}, {2'd0}};

assign tmp_s_fu_121_p1 = tmp_fu_113_p3;

always @ (posedge ap_clk) begin
    state_addr_reg_203[1:0] <= 2'b00;
    state_addr_1_reg_208[1:0] <= 2'b11;
end

endmodule //aes128_shift_rows_hw
