// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _aes128_add_round_key_HH_
#define _aes128_add_round_key_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct aes128_add_round_key : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > state_address0;
    sc_out< sc_logic > state_ce0;
    sc_out< sc_logic > state_we0;
    sc_out< sc_lv<8> > state_d0;
    sc_in< sc_lv<8> > state_q0;
    sc_out< sc_lv<4> > state_address1;
    sc_out< sc_logic > state_ce1;
    sc_out< sc_logic > state_we1;
    sc_out< sc_lv<8> > state_d1;
    sc_in< sc_lv<8> > state_q1;
    sc_out< sc_lv<4> > round_key_address0;
    sc_out< sc_logic > round_key_ce0;
    sc_in< sc_lv<8> > round_key_q0;
    sc_out< sc_lv<4> > round_key_address1;
    sc_out< sc_logic > round_key_ce1;
    sc_in< sc_lv<8> > round_key_q1;


    // Module declarations
    aes128_add_round_key(sc_module_name name);
    SC_HAS_PROCESS(aes128_add_round_key);

    ~aes128_add_round_key();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > grp_fu_115_p2;
    sc_signal< sc_lv<8> > reg_127;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<8> > grp_fu_121_p2;
    sc_signal< sc_lv<8> > reg_132;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > exitcond_fu_137_p2;
    sc_signal< sc_lv<4> > state_addr_reg_201;
    sc_signal< sc_lv<4> > tmp_16_fu_149_p1;
    sc_signal< sc_lv<4> > tmp_16_reg_206;
    sc_signal< sc_lv<4> > state_addr_34_reg_217;
    sc_signal< sc_lv<5> > i_15_3_fu_165_p2;
    sc_signal< sc_lv<5> > i_15_3_reg_222;
    sc_signal< sc_lv<4> > state_addr_35_reg_232;
    sc_signal< sc_lv<4> > state_addr_36_reg_242;
    sc_signal< sc_lv<5> > i_reg_104;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > tmp_fu_143_p1;
    sc_signal< sc_lv<64> > tmp_1_fu_159_p1;
    sc_signal< sc_lv<64> > tmp_2_fu_176_p1;
    sc_signal< sc_lv<64> > tmp_3_fu_187_p1;
    sc_signal< sc_lv<4> > i_15_s_fu_153_p2;
    sc_signal< sc_lv<4> > i_15_1_fu_171_p2;
    sc_signal< sc_lv<4> > i_15_2_fu_182_p2;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_state4;
    static const sc_lv<5> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<5> ap_const_lv5_4;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond_fu_137_p2();
    void thread_grp_fu_115_p2();
    void thread_grp_fu_121_p2();
    void thread_i_15_1_fu_171_p2();
    void thread_i_15_2_fu_182_p2();
    void thread_i_15_3_fu_165_p2();
    void thread_i_15_s_fu_153_p2();
    void thread_round_key_address0();
    void thread_round_key_address1();
    void thread_round_key_ce0();
    void thread_round_key_ce1();
    void thread_state_address0();
    void thread_state_address1();
    void thread_state_ce0();
    void thread_state_ce1();
    void thread_state_d0();
    void thread_state_d1();
    void thread_state_we0();
    void thread_state_we1();
    void thread_tmp_16_fu_149_p1();
    void thread_tmp_1_fu_159_p1();
    void thread_tmp_2_fu_176_p1();
    void thread_tmp_3_fu_187_p1();
    void thread_tmp_fu_143_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
