// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "aes128_mix_column_hw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic aes128_mix_column_hw::ap_const_logic_1 = sc_dt::Log_1;
const bool aes128_mix_column_hw::ap_const_boolean_1 = true;
const sc_lv<3> aes128_mix_column_hw::ap_const_lv3_2 = "10";
const sc_lv<3> aes128_mix_column_hw::ap_const_lv3_3 = "11";
const sc_lv<3> aes128_mix_column_hw::ap_const_lv3_1 = "1";
const sc_logic aes128_mix_column_hw::ap_const_logic_0 = sc_dt::Log_0;

aes128_mix_column_hw::aes128_mix_column_hw(sc_module_name name) : sc_module(name), mVcdFile(0) {
    tmp_gmul_hw_fu_44 = new gmul_hw("tmp_gmul_hw_fu_44");
    tmp_gmul_hw_fu_44->ap_ready(tmp_gmul_hw_fu_44_ap_ready);
    tmp_gmul_hw_fu_44->a(column_0_read);
    tmp_gmul_hw_fu_44->b(ap_var_for_const0);
    tmp_gmul_hw_fu_44->ap_return(tmp_gmul_hw_fu_44_ap_return);
    tmp_s_gmul_hw_fu_52 = new gmul_hw("tmp_s_gmul_hw_fu_52");
    tmp_s_gmul_hw_fu_52->ap_ready(tmp_s_gmul_hw_fu_52_ap_ready);
    tmp_s_gmul_hw_fu_52->a(column_1_read);
    tmp_s_gmul_hw_fu_52->b(ap_var_for_const1);
    tmp_s_gmul_hw_fu_52->ap_return(tmp_s_gmul_hw_fu_52_ap_return);
    tmp_9_gmul_hw_fu_60 = new gmul_hw("tmp_9_gmul_hw_fu_60");
    tmp_9_gmul_hw_fu_60->ap_ready(tmp_9_gmul_hw_fu_60_ap_ready);
    tmp_9_gmul_hw_fu_60->a(column_2_read);
    tmp_9_gmul_hw_fu_60->b(ap_var_for_const2);
    tmp_9_gmul_hw_fu_60->ap_return(tmp_9_gmul_hw_fu_60_ap_return);
    tmp_1_gmul_hw_fu_68 = new gmul_hw("tmp_1_gmul_hw_fu_68");
    tmp_1_gmul_hw_fu_68->ap_ready(tmp_1_gmul_hw_fu_68_ap_ready);
    tmp_1_gmul_hw_fu_68->a(column_3_read);
    tmp_1_gmul_hw_fu_68->b(ap_var_for_const2);
    tmp_1_gmul_hw_fu_68->ap_return(tmp_1_gmul_hw_fu_68_ap_return);
    tmp_4_gmul_hw_fu_76 = new gmul_hw("tmp_4_gmul_hw_fu_76");
    tmp_4_gmul_hw_fu_76->ap_ready(tmp_4_gmul_hw_fu_76_ap_ready);
    tmp_4_gmul_hw_fu_76->a(column_0_read);
    tmp_4_gmul_hw_fu_76->b(ap_var_for_const2);
    tmp_4_gmul_hw_fu_76->ap_return(tmp_4_gmul_hw_fu_76_ap_return);
    tmp_5_gmul_hw_fu_84 = new gmul_hw("tmp_5_gmul_hw_fu_84");
    tmp_5_gmul_hw_fu_84->ap_ready(tmp_5_gmul_hw_fu_84_ap_ready);
    tmp_5_gmul_hw_fu_84->a(column_1_read);
    tmp_5_gmul_hw_fu_84->b(ap_var_for_const0);
    tmp_5_gmul_hw_fu_84->ap_return(tmp_5_gmul_hw_fu_84_ap_return);
    tmp_6_gmul_hw_fu_92 = new gmul_hw("tmp_6_gmul_hw_fu_92");
    tmp_6_gmul_hw_fu_92->ap_ready(tmp_6_gmul_hw_fu_92_ap_ready);
    tmp_6_gmul_hw_fu_92->a(column_2_read);
    tmp_6_gmul_hw_fu_92->b(ap_var_for_const1);
    tmp_6_gmul_hw_fu_92->ap_return(tmp_6_gmul_hw_fu_92_ap_return);
    tmp_2_gmul_hw_fu_100 = new gmul_hw("tmp_2_gmul_hw_fu_100");
    tmp_2_gmul_hw_fu_100->ap_ready(tmp_2_gmul_hw_fu_100_ap_ready);
    tmp_2_gmul_hw_fu_100->a(column_1_read);
    tmp_2_gmul_hw_fu_100->b(ap_var_for_const2);
    tmp_2_gmul_hw_fu_100->ap_return(tmp_2_gmul_hw_fu_100_ap_return);
    tmp_3_gmul_hw_fu_108 = new gmul_hw("tmp_3_gmul_hw_fu_108");
    tmp_3_gmul_hw_fu_108->ap_ready(tmp_3_gmul_hw_fu_108_ap_ready);
    tmp_3_gmul_hw_fu_108->a(column_2_read);
    tmp_3_gmul_hw_fu_108->b(ap_var_for_const0);
    tmp_3_gmul_hw_fu_108->ap_return(tmp_3_gmul_hw_fu_108_ap_return);
    tmp_7_gmul_hw_fu_116 = new gmul_hw("tmp_7_gmul_hw_fu_116");
    tmp_7_gmul_hw_fu_116->ap_ready(tmp_7_gmul_hw_fu_116_ap_ready);
    tmp_7_gmul_hw_fu_116->a(column_3_read);
    tmp_7_gmul_hw_fu_116->b(ap_var_for_const1);
    tmp_7_gmul_hw_fu_116->ap_return(tmp_7_gmul_hw_fu_116_ap_return);
    tmp_8_gmul_hw_fu_124 = new gmul_hw("tmp_8_gmul_hw_fu_124");
    tmp_8_gmul_hw_fu_124->ap_ready(tmp_8_gmul_hw_fu_124_ap_ready);
    tmp_8_gmul_hw_fu_124->a(column_0_read);
    tmp_8_gmul_hw_fu_124->b(ap_var_for_const1);
    tmp_8_gmul_hw_fu_124->ap_return(tmp_8_gmul_hw_fu_124_ap_return);
    tmp_10_gmul_hw_fu_132 = new gmul_hw("tmp_10_gmul_hw_fu_132");
    tmp_10_gmul_hw_fu_132->ap_ready(tmp_10_gmul_hw_fu_132_ap_ready);
    tmp_10_gmul_hw_fu_132->a(column_3_read);
    tmp_10_gmul_hw_fu_132->b(ap_var_for_const0);
    tmp_10_gmul_hw_fu_132->ap_return(tmp_10_gmul_hw_fu_132_ap_return);

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( column_0_write_assi_fu_152_p2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( column_1_write_assi_fu_170_p2 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( column_2_write_assi_fu_188_p2 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( column_3_write_assi_fu_206_p2 );

    SC_METHOD(thread_column_0_write_assi_fu_152_p2);
    sensitive << ( tmp2_fu_146_p2 );
    sensitive << ( tmp1_fu_140_p2 );

    SC_METHOD(thread_column_1_write_assi_fu_170_p2);
    sensitive << ( tmp4_fu_164_p2 );
    sensitive << ( tmp3_fu_158_p2 );

    SC_METHOD(thread_column_2_write_assi_fu_188_p2);
    sensitive << ( tmp6_fu_182_p2 );
    sensitive << ( tmp5_fu_176_p2 );

    SC_METHOD(thread_column_3_write_assi_fu_206_p2);
    sensitive << ( tmp8_fu_200_p2 );
    sensitive << ( tmp7_fu_194_p2 );

    SC_METHOD(thread_tmp1_fu_140_p2);
    sensitive << ( tmp_gmul_hw_fu_44_ap_return );
    sensitive << ( tmp_s_gmul_hw_fu_52_ap_return );

    SC_METHOD(thread_tmp2_fu_146_p2);
    sensitive << ( tmp_9_gmul_hw_fu_60_ap_return );
    sensitive << ( tmp_1_gmul_hw_fu_68_ap_return );

    SC_METHOD(thread_tmp3_fu_158_p2);
    sensitive << ( tmp_4_gmul_hw_fu_76_ap_return );
    sensitive << ( tmp_5_gmul_hw_fu_84_ap_return );

    SC_METHOD(thread_tmp4_fu_164_p2);
    sensitive << ( tmp_1_gmul_hw_fu_68_ap_return );
    sensitive << ( tmp_6_gmul_hw_fu_92_ap_return );

    SC_METHOD(thread_tmp5_fu_176_p2);
    sensitive << ( tmp_4_gmul_hw_fu_76_ap_return );
    sensitive << ( tmp_2_gmul_hw_fu_100_ap_return );

    SC_METHOD(thread_tmp6_fu_182_p2);
    sensitive << ( tmp_3_gmul_hw_fu_108_ap_return );
    sensitive << ( tmp_7_gmul_hw_fu_116_ap_return );

    SC_METHOD(thread_tmp7_fu_194_p2);
    sensitive << ( tmp_2_gmul_hw_fu_100_ap_return );
    sensitive << ( tmp_8_gmul_hw_fu_124_ap_return );

    SC_METHOD(thread_tmp8_fu_200_p2);
    sensitive << ( tmp_9_gmul_hw_fu_60_ap_return );
    sensitive << ( tmp_10_gmul_hw_fu_132_ap_return );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "aes128_mix_column_hw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, column_0_read, "(port)column_0_read");
    sc_trace(mVcdFile, column_1_read, "(port)column_1_read");
    sc_trace(mVcdFile, column_2_read, "(port)column_2_read");
    sc_trace(mVcdFile, column_3_read, "(port)column_3_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, tmp_gmul_hw_fu_44_ap_ready, "tmp_gmul_hw_fu_44_ap_ready");
    sc_trace(mVcdFile, tmp_gmul_hw_fu_44_ap_return, "tmp_gmul_hw_fu_44_ap_return");
    sc_trace(mVcdFile, tmp_s_gmul_hw_fu_52_ap_ready, "tmp_s_gmul_hw_fu_52_ap_ready");
    sc_trace(mVcdFile, tmp_s_gmul_hw_fu_52_ap_return, "tmp_s_gmul_hw_fu_52_ap_return");
    sc_trace(mVcdFile, tmp_9_gmul_hw_fu_60_ap_ready, "tmp_9_gmul_hw_fu_60_ap_ready");
    sc_trace(mVcdFile, tmp_9_gmul_hw_fu_60_ap_return, "tmp_9_gmul_hw_fu_60_ap_return");
    sc_trace(mVcdFile, tmp_1_gmul_hw_fu_68_ap_ready, "tmp_1_gmul_hw_fu_68_ap_ready");
    sc_trace(mVcdFile, tmp_1_gmul_hw_fu_68_ap_return, "tmp_1_gmul_hw_fu_68_ap_return");
    sc_trace(mVcdFile, tmp_4_gmul_hw_fu_76_ap_ready, "tmp_4_gmul_hw_fu_76_ap_ready");
    sc_trace(mVcdFile, tmp_4_gmul_hw_fu_76_ap_return, "tmp_4_gmul_hw_fu_76_ap_return");
    sc_trace(mVcdFile, tmp_5_gmul_hw_fu_84_ap_ready, "tmp_5_gmul_hw_fu_84_ap_ready");
    sc_trace(mVcdFile, tmp_5_gmul_hw_fu_84_ap_return, "tmp_5_gmul_hw_fu_84_ap_return");
    sc_trace(mVcdFile, tmp_6_gmul_hw_fu_92_ap_ready, "tmp_6_gmul_hw_fu_92_ap_ready");
    sc_trace(mVcdFile, tmp_6_gmul_hw_fu_92_ap_return, "tmp_6_gmul_hw_fu_92_ap_return");
    sc_trace(mVcdFile, tmp_2_gmul_hw_fu_100_ap_ready, "tmp_2_gmul_hw_fu_100_ap_ready");
    sc_trace(mVcdFile, tmp_2_gmul_hw_fu_100_ap_return, "tmp_2_gmul_hw_fu_100_ap_return");
    sc_trace(mVcdFile, tmp_3_gmul_hw_fu_108_ap_ready, "tmp_3_gmul_hw_fu_108_ap_ready");
    sc_trace(mVcdFile, tmp_3_gmul_hw_fu_108_ap_return, "tmp_3_gmul_hw_fu_108_ap_return");
    sc_trace(mVcdFile, tmp_7_gmul_hw_fu_116_ap_ready, "tmp_7_gmul_hw_fu_116_ap_ready");
    sc_trace(mVcdFile, tmp_7_gmul_hw_fu_116_ap_return, "tmp_7_gmul_hw_fu_116_ap_return");
    sc_trace(mVcdFile, tmp_8_gmul_hw_fu_124_ap_ready, "tmp_8_gmul_hw_fu_124_ap_ready");
    sc_trace(mVcdFile, tmp_8_gmul_hw_fu_124_ap_return, "tmp_8_gmul_hw_fu_124_ap_return");
    sc_trace(mVcdFile, tmp_10_gmul_hw_fu_132_ap_ready, "tmp_10_gmul_hw_fu_132_ap_ready");
    sc_trace(mVcdFile, tmp_10_gmul_hw_fu_132_ap_return, "tmp_10_gmul_hw_fu_132_ap_return");
    sc_trace(mVcdFile, tmp2_fu_146_p2, "tmp2_fu_146_p2");
    sc_trace(mVcdFile, tmp1_fu_140_p2, "tmp1_fu_140_p2");
    sc_trace(mVcdFile, tmp4_fu_164_p2, "tmp4_fu_164_p2");
    sc_trace(mVcdFile, tmp3_fu_158_p2, "tmp3_fu_158_p2");
    sc_trace(mVcdFile, tmp6_fu_182_p2, "tmp6_fu_182_p2");
    sc_trace(mVcdFile, tmp5_fu_176_p2, "tmp5_fu_176_p2");
    sc_trace(mVcdFile, tmp8_fu_200_p2, "tmp8_fu_200_p2");
    sc_trace(mVcdFile, tmp7_fu_194_p2, "tmp7_fu_194_p2");
    sc_trace(mVcdFile, column_0_write_assi_fu_152_p2, "column_0_write_assi_fu_152_p2");
    sc_trace(mVcdFile, column_1_write_assi_fu_170_p2, "column_1_write_assi_fu_170_p2");
    sc_trace(mVcdFile, column_2_write_assi_fu_188_p2, "column_2_write_assi_fu_188_p2");
    sc_trace(mVcdFile, column_3_write_assi_fu_206_p2, "column_3_write_assi_fu_206_p2");
#endif

    }
}

aes128_mix_column_hw::~aes128_mix_column_hw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete tmp_gmul_hw_fu_44;
    delete tmp_s_gmul_hw_fu_52;
    delete tmp_9_gmul_hw_fu_60;
    delete tmp_1_gmul_hw_fu_68;
    delete tmp_4_gmul_hw_fu_76;
    delete tmp_5_gmul_hw_fu_84;
    delete tmp_6_gmul_hw_fu_92;
    delete tmp_2_gmul_hw_fu_100;
    delete tmp_3_gmul_hw_fu_108;
    delete tmp_7_gmul_hw_fu_116;
    delete tmp_8_gmul_hw_fu_124;
    delete tmp_10_gmul_hw_fu_132;
}

void aes128_mix_column_hw::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv3_2;
}

void aes128_mix_column_hw::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv3_3;
}

void aes128_mix_column_hw::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv3_1;
}

void aes128_mix_column_hw::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void aes128_mix_column_hw::thread_ap_return_0() {
    ap_return_0 = column_0_write_assi_fu_152_p2.read();
}

void aes128_mix_column_hw::thread_ap_return_1() {
    ap_return_1 = column_1_write_assi_fu_170_p2.read();
}

void aes128_mix_column_hw::thread_ap_return_2() {
    ap_return_2 = column_2_write_assi_fu_188_p2.read();
}

void aes128_mix_column_hw::thread_ap_return_3() {
    ap_return_3 = column_3_write_assi_fu_206_p2.read();
}

void aes128_mix_column_hw::thread_column_0_write_assi_fu_152_p2() {
    column_0_write_assi_fu_152_p2 = (tmp2_fu_146_p2.read() ^ tmp1_fu_140_p2.read());
}

void aes128_mix_column_hw::thread_column_1_write_assi_fu_170_p2() {
    column_1_write_assi_fu_170_p2 = (tmp4_fu_164_p2.read() ^ tmp3_fu_158_p2.read());
}

void aes128_mix_column_hw::thread_column_2_write_assi_fu_188_p2() {
    column_2_write_assi_fu_188_p2 = (tmp6_fu_182_p2.read() ^ tmp5_fu_176_p2.read());
}

void aes128_mix_column_hw::thread_column_3_write_assi_fu_206_p2() {
    column_3_write_assi_fu_206_p2 = (tmp8_fu_200_p2.read() ^ tmp7_fu_194_p2.read());
}

void aes128_mix_column_hw::thread_tmp1_fu_140_p2() {
    tmp1_fu_140_p2 = (tmp_s_gmul_hw_fu_52_ap_return.read() ^ tmp_gmul_hw_fu_44_ap_return.read());
}

void aes128_mix_column_hw::thread_tmp2_fu_146_p2() {
    tmp2_fu_146_p2 = (tmp_9_gmul_hw_fu_60_ap_return.read() ^ tmp_1_gmul_hw_fu_68_ap_return.read());
}

void aes128_mix_column_hw::thread_tmp3_fu_158_p2() {
    tmp3_fu_158_p2 = (tmp_5_gmul_hw_fu_84_ap_return.read() ^ tmp_4_gmul_hw_fu_76_ap_return.read());
}

void aes128_mix_column_hw::thread_tmp4_fu_164_p2() {
    tmp4_fu_164_p2 = (tmp_6_gmul_hw_fu_92_ap_return.read() ^ tmp_1_gmul_hw_fu_68_ap_return.read());
}

void aes128_mix_column_hw::thread_tmp5_fu_176_p2() {
    tmp5_fu_176_p2 = (tmp_2_gmul_hw_fu_100_ap_return.read() ^ tmp_4_gmul_hw_fu_76_ap_return.read());
}

void aes128_mix_column_hw::thread_tmp6_fu_182_p2() {
    tmp6_fu_182_p2 = (tmp_3_gmul_hw_fu_108_ap_return.read() ^ tmp_7_gmul_hw_fu_116_ap_return.read());
}

void aes128_mix_column_hw::thread_tmp7_fu_194_p2() {
    tmp7_fu_194_p2 = (tmp_2_gmul_hw_fu_100_ap_return.read() ^ tmp_8_gmul_hw_fu_124_ap_return.read());
}

void aes128_mix_column_hw::thread_tmp8_fu_200_p2() {
    tmp8_fu_200_p2 = (tmp_9_gmul_hw_fu_60_ap_return.read() ^ tmp_10_gmul_hw_fu_132_ap_return.read());
}

}

