// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gmul_hw (
        ap_ready,
        a,
        b,
        ap_return
);


output   ap_ready;
input  [7:0] a;
input  [2:0] b;
output  [7:0] ap_return;

wire   [0:0] tmp_fu_34_p1;
wire   [7:0] tmp_2_fu_54_p2;
wire   [0:0] tmp_1_fu_46_p3;
wire   [7:0] a_assign_fu_60_p2;
wire   [0:0] tmp_3_fu_74_p3;
wire   [7:0] p_1_fu_66_p3;
wire   [7:0] tmp_5_fu_38_p3;
wire   [7:0] tmp_5_1_fu_82_p3;

assign a_assign_fu_60_p2 = (tmp_2_fu_54_p2 ^ 8'd27);

assign ap_ready = 1'b1;

assign ap_return = (tmp_5_fu_38_p3 ^ tmp_5_1_fu_82_p3);

assign p_1_fu_66_p3 = ((tmp_1_fu_46_p3[0:0] === 1'b1) ? a_assign_fu_60_p2 : tmp_2_fu_54_p2);

assign tmp_1_fu_46_p3 = a[32'd7];

assign tmp_2_fu_54_p2 = a << 8'd1;

assign tmp_3_fu_74_p3 = b[32'd1];

assign tmp_5_1_fu_82_p3 = ((tmp_3_fu_74_p3[0:0] === 1'b1) ? p_1_fu_66_p3 : 8'd0);

assign tmp_5_fu_38_p3 = ((tmp_fu_34_p1[0:0] === 1'b1) ? a : 8'd0);

assign tmp_fu_34_p1 = b[0:0];

endmodule //gmul_hw
